apiVersion: apps/v1
kind: Deployment
metadata:
  name: solo-leveling-ai
spec:
  replicas: ${REPLICAS}
  selector:
    matchLabels:
      app: solo-leveling-ai
  template:
    metadata:
      labels:
        app: solo-leveling-ai
      annotations:
        commit.sha: "${GIT_COMMIT_SHA}"
    spec:
      containers:
        - name: app
          image: $DOCKERHUB_USER/solo-leveling-ai:$GIT_COMMIT_SHA
          ports:
            - containerPort: 8080
          env:
            - name: OPENROUTER_TOKEN
              value: "${OPENROUTER_TOKEN}"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5